query GetBoxes {
	boxCollection(first: 100) {
		edges {
			node {
				id
				name
				description
				contents(first: 100) {
					edges {
						node {
							id
							name
						}
					}
				}
			}
		}
	}
}
